region: us-west-2
parameter_prefix: /robotics-aws
project_name: robotics-aws
launch_templates:
  gazebo: robotics-aws-gazebo-lt
  isaac: robotics-aws-isaac-lt
allowed_instance_types:
  gazebo:
    - g4dn.xlarge
    - g4dn.2xlarge
    - g5.xlarge
    - g5.2xlarge
  isaac:
    - g6e.xlarge
    - g6e.2xlarge
    - g7e.xlarge
s3:
  project_prefix: project/
  workspace_path: /workspace/project
webrtc:
  public_port: 8211
